### ISSUE TITLE
operation timed out

### ISSUE THREAD

**Issue by gse-cc-git** [untitaker/mastodon-bookmark-rss#1]
Hello,

I pulled the docker image on my system to run it and hopefully generate a rss-feed from my bookmarks. I intended to use Thunderbird as a RSS reader.

I connect sucessfully in Firefox, fill the fields 
```
http://172.17.0.2:3000/feed?host=<the.instance.im.using>&token=<the.token.string>
```

I get the following error
```
request to your mastodon instance failed: error sending request for url (https://<the.instance.im.using>/api/v1/bookmarks): operation timed out
```

I tested w/wo proxy & firewall without much success.

Any idea ?

Thanks for your work.

**Comment by gse-cc-git** [comment]
mamot.fr

**Comment by untitaker** [comment]
ok, do you perhaps have a ton of bookmarks? that server does load fine for me in general. does my hosted service work?

**Comment by gse-cc-git** [comment]
225 bookmarks so far. 
Your hosted service does work but I cannot successfully import the feed in TB (it doesn't pass the check)

**Comment by gse-cc-git** [comment]
When I add the flux address generated by your hosted service in thunderbird I get:
`The flux address is not valid` 
What I understand is that TB sends the address to `https://validator.w3.org/` which returns a diagnostic `Sorry This feed does not validate.` while listing all issues like:

```
[line 12], column 14: link must be a full and valid URL: [[help](https://validator.w3.org/feed/docs/error/InvalidFullLink.html)]
           <link></link>
```

**Comment by untitaker** [comment]
ok, i didn't think that thunderbird would care about that. it should be fixed in https://github.com/untitaker/mastodon-bookmark-rss/commit/6a83c6119f84211ed6eecb0e1ce9fb585f1a385b. can you try again (on my hosted service)?

I do not know what to do about the timeout errors on your deployment, this seems like it would be best investigated by somebody other than me.

**Comment by gse-cc-git** [comment]
@untitaker thanks for your answers !
I'll  check `6a83c61` and let you know.

About timeouts: I will continue to test.
