### ISSUE TITLE
Make RSS article link go to first link in status?

### ISSUE THREAD

**Issue by untitaker** [untitaker/mastodon-bookmark-rss#2]
I partially use Mastodon as a glorified link aggregator, so sometimes I bookmark statuses that link articles I want to read.

I wonder whether it would make sense to make the RSS feed's items go to whichever link is posted within the bookmarked status (by looking at the attached link preview) rather than the status URL.

If there is no link, it would fall back to the status link.

This would make it possible to use the Load Full Content feature in Inoreader for that particular usecase more effectively.

Perhaps make it configurable? Need feedback on it.

**Comment by norz** [comment]
Yes, very good idea ! 👍 🙏 

It works very nicely with my RSS reeder app. 😊  

(NB: some (micro)blogs also have adopted this behaviour, e.g.: Daring Fireball by Gruber, and [Louis Derrac’s](https://veille.louisderrac.com/))

**Comment by untitaker** [comment]
I forgot I had this issue open. I already implemented it with https://github.com/untitaker/mastodon-bookmark-rss/commit/e634dafaf171b5177af37273d976b0d57387d9ca
