### ISSUE TITLE
Convert csv of older bookmarks into an RSS feed

### ISSUE THREAD

**Issue by moosebegab** [untitaker/mastodon-bookmark-rss#5]
https://www.reddit.com/r/Mastodon/comments/10y6hg6/comment/k2a11f2/?utm_source=share&utm_medium=web2x&context=3

```
yeah it only shows 20 bookmarks. I could add more (i.e. go through all pages of bookmarks) but I feel that it would be abusive towards the mastodon server if this happened on every fetch of the feed. and I also don't have any state management or caching in place.

For me it is mainly about the automation of adding new bookmarks into my reading list. I think you could convert the csv into an RSS feed but it is not quite the same structure, so I believe it might be best to write a separate tool to convert them.

feel free to file a ticket on github though
```
feature request

**Comment by untitaker** [comment]
thinking about this a bit more. is the goal here to just have toot content and contained links stored _somewhere_, or is inoreader the actual preferred option here?

**Comment by moosebegab** [comment]
that's a really good question.

I often bookmark posts that contain info I want to look up later or links I want to check out later.  But I tend to not check out the bookmark column unless I specifically think of something I bookmarked.

I like the idea of having them in the feed because it shows the content. I can then save or delete.

But, I think I'm overthinking this and creating unnecessary work. So I will take back my request. 

Thanks again for your Bookmark RSS tool. 🥇

**Comment by untitaker** [comment]
I am still not entirely sure of the goal, but if you just want to be able to search your bookmarks by content, mastodon should provide that. If you want to do that _offline_, I just now wrote a small tool to export contents of your bookmarks as `.jsonl` file, which should be importable into Excel or similar tools.

https://untitaker.github.io/mastodon-bookmark-export/

I think though that this sort of tool should be used sparingly since it's somewhat resource-intensive (for server owners of the respective posts, not for me), and it is also only capable of fetching contents of public posts.

**Comment by toddz262** [comment]
> only shows 20 bookmarks

I came here to ask if only 20 bookmarks showed up by design. I don't think this limit is noted in the readme... might be worth a mention.  (And thanks for the export converter -- that should get me caught up.)

**Comment by untitaker** [comment]
> I came here to ask if only 20 bookmarks showed up by design. I don't think this limit is noted in the readme... might be worth a mention. (And thanks for the export converter -- that should get me caught up.)

feel free to make a pr against the readme with whatever language you think clarifies this best. i always sort of assume that rss feeds are used for receiving updates and not for a total view of the full state.

**Comment by toddz262** [comment]
> ... rss feeds... for receiving updates and not for a total view of the full state

This is reasonable. I'd just gotten used to leaning on unlimited feeds as an archive, which is probably more of a cheat than a best practice.
